### ISSUE TITLE
To keep placeholder comments especially for include

### ISSUE THREAD

**Issue by kalidema** [dciccale/grunt-processhtml#101]
Is there any possibility to keep placeholder comments especially for include. Let's take a hypothetical case. If I am developing a template which has a header or sidebar region wherein they are all nav links, search box… 

These regions are repeated on every page but also are updated very often. It will be great to keep comments until dist task, because I would like to include this part during development to see the changes. This is the reason why for me placeholder comments are necessary until distribution. Perhaps you could consider in the future as additional option. A simple solution could be e.g.
grunt.initConfig({
  processhtml: {
    dev: {
      options: {
        stripPlaceholder: false
      }
    },
    dist: {
      options: {
        stripPlaceholder: true
      }
    }
  },
});

**Comment by dciccale** [comment]
I think I didn't get what you need.

if you target your comments between different environments `dist` `dev` or whatever, and you run `grunt processhtml:dev` only `dev` targets will be affected.

**Comment by dciccale** [comment]
anything new here ? how can i help

**Comment by dciccale** [comment]
feel free to re-open in case of further discussion. thanks for your contribution

**Comment by askalburgi** [comment]
I think I'm trying to do something similar. 

I want to add a line to my html file, and retain the ability to add another line. 

So I have: 
`<a href="#" onclick="document.getElementById('theme').setAttribute('href','themes/moon.css'); return false;">Moon</a>,
`

And I want it to become: 
`<a href="#" onclick="document.getElementById('theme').setAttribute('href','themes/moon.css'); return false;">Moon</a>,
<a href="#" onclick="document.getElementById('theme').setAttribute('href','themes/solarized.css'); return false;">Solarized</a>,
`


So what I've done in my grunt is: 
`processhtml: {
	options: {
		data: {
			newTheme: themelink
		}
	}
	....
`

Where themelink is:
`var themelink = "- <a href='#'' onclick=\"document.getElementById('theme').setAttribute('href','themes/"+themename+".css'); return false;\">"+themename.charAt(0).toUpperCase()+themename.slice(1)+"</a> \n\
	"`

The problem is processhtml tries to replace the newTheme in themelink too! So I get a `newTheme not defined` warning and thus doesn't run.
