### ISSUE TITLE
Strip option with template

### ISSUE THREAD

**Issue by luiscoms** [dciccale/grunt-processhtml#53]
I just try to set strip option to true and does not work with template

        

And when run another target 'some code' stay at document.

**Comment by nathggns** [comment]
This is biting me in the ass now. I don't see why this issue is closed as its very much an issue. You currently cannot have a template that is removed when a different target is used. I've tried combining `build:remove` and `build:template` with `strip` set to both `true` and `false` and no combination works.

**Comment by agreif84** [comment]
I agree with @nathggns and @luiscoms
Well I think the strip-option acts confusing since the comments work diffenrently when you use a template:
- Remove: `<!-- build:remove:dist -->` (comment closed)
- Template: `<!-- build:template:dist` (comment not closed)
I also ran into the trap assuming "strip: true" would strip the whole block as the comment is not closed. It seems this behaviour is intended. So maybe you can create another option "stripTemplate" that strips the template-block as well.

**Comment by dciccale** [comment]
First of all, template comments are not closed because lodash template syntax is not valid html and will break your html from rendering and that is not what you want. Is not an issue nor a bug having the template block not closed.

I will take a further look into the fact that template blocks are not being stripped when the current env doesn't match the block and strip is true.

**Comment by dciccale** [comment]
in fact, we can't just strip template comments. because of the same reason they are not closed in the first place.

if the processed file for the matching target didn't meant to process the template and we strip the comments (imagine we could, given the fact that the comment opened) the template will break your html.

so what I suggest, is you could use other blocks to achieve the same thing.

if there are no further questions may I close the issue? :)

any ideas from your side guys?

thx

**Comment by agreif84** [comment]
After I thought about the problem and your argumentation for a while, I agree with you. I played around a bit and yeah, we just can't strip the whole template comments. This would not work the way processhtml (and the strip-option) is meant to be.

But this leads me to rethink my deployment-process. Actually, I can't have a block that is hidden/commented in my development-environment (where processhtml won't process any file). e.g. tracking-code that I want to be added when my HTML is being deployed to the live-environment (although I know I can exclude my pageviews otherwise - this is only an example).

So I might search for another solution. You may close this issue.

**Comment by dciccale** [comment]
Just one last comment, you could include your tracking-code in live-environment as follows:

`template.html`

```html
<html>
  <head>
    <!-- build:include:prod tracking-code.html -->
    <!-- /build -->
  </head>
</html>
```

with following grunt options:

```js
      prod: {
        options: {
          strip: true
        },
        files: [{
          'dist/index.html': ['template.html']
        }]
      },
      dev: {
        options: {
          strip: true
        },
        files: [{
          'dist/index.html': ['template.html']
        }]
      },
```

this will include you tracking-code in production, and remove the include block in dev to keep it clean

**Comment by agreif84** [comment]
Thanks a lot!
